# SPDX-FileCopyrightText: 2024 Wiktor Kwapisiewicz <wiktor@metacode.biz>
# SPDX-License-Identifier: CC0-1.0

[advisories]
unmaintained = "deny"
yanked = "deny"
ignore = [
]

[bans]
deny = [
]

[licenses]
allow = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "MIT",
  "Unicode-DFS-2016",
  "ISC",
  "BSD-3-Clause",
]
