# SPDX-FileCopyrightText: 2024 Wiktor Kwapisiewicz <wiktor@metacode.biz>
# SPDX-License-Identifier: CC0-1.0

name: Check

on:
  pull_request:
  push:
    tags:
      - 'v*'
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Build & test
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: pacman -Sy --needed --noconfirm archlinux-keyring
      - run: pacman -Syu --needed --noconfirm just
      - run: just install
      - run: ./init-mssim.sh && CARGO_TARGET_DIR=/tmp/cargo just ci
      # release if we're building a tag
      - if: "startsWith(github.ref, 'refs/tags/')"
        run: cargo install cargo-edit && \
             cargo set-version "${GITHUB_REF:11}" && \
             cargo publish --allow-dirty --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
